[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "gcc"]

[phases.install]
cmds = ["python -m ensurepip --upgrade", "pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT" 